services:
  db:
    extends:
      file: compose.base.yaml
      service: db
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432:5433
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8090:8080
  backend:
    extends:
      file: compose.base.yaml
      service: backend
  nginx:
    image: nginx:1.29.1-alpine
    container_name: antifraud-nginx
    ports:
        - "8080:8080"
    volumes:
        - ./.config/dev/nginx.dev.conf:/etc/nginx/nginx.conf
        - static_volume:/var/www/backend/static
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost/ping/" ]
        interval: 4s
    restart: on-failure
    depends_on:
      backend:
        condition: service_started
  redis:
    extends:
      file: compose.base.yaml
      service: redis
    volumes:
      - redis-data:/data

volumes:
    static_volume:
    db-data:
    redis-data: